# Generated by Django 5.2.13 on 2026-05-03 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('city_slug', models.SlugField(max_length=100)),
                ('city_label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('cover_image_url', models.URLField(blank=True)),
                ('cuisine_type', models.CharField(blank=True, max_length=100)),
                ('price_range', models.CharField(blank=True, help_text='€, €€, €€€', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'restaurants_venue',
                'ordering': ['city_slug', 'name'],
                'unique_together': {('city_slug', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='RestaurantTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('capacity', models.PositiveIntegerField(default=4)),
                ('confirmed_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('OPEN', 'Disponible'), ('FULL', 'Complet'), ('CLOSED', 'Fermé')], default='OPEN', max_length=10)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='restaurants.restaurantvenue')),
            ],
            options={
                'db_table': 'restaurants_timeslot',
                'ordering': ['date', 'time'],
                'unique_together': {('venue', 'date', 'time')},
            },
        ),
    ]
