# Generated by Django 5.2.13 on 2026-05-18 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantvenue',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_restaurants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restaurantvenue',
            name='reservation_mode',
            field=models.CharField(choices=[('AUTO', 'Automatique'), ('MANUAL', 'Validation manuelle')], default='AUTO', max_length=10),
        ),
    ]
