# Generated by Django 5.2.13 on 2026-05-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('city', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('cover_image_url', models.URLField(blank=True)),
                ('price', models.PositiveIntegerField(default=0, help_text='Price in cents. 0 = free.')),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PUBLISHED', 'Publié'), ('CANCELLED', 'Annulé'), ('COMPLETED', 'Terminé')], default='DRAFT', max_length=20)),
                ('is_partner_event', models.BooleanField(default=False)),
                ('partner_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'events_event',
                'ordering': ['starts_at'],
            },
        ),
    ]
