# Generated by Django 5.2.13 on 2026-05-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='stripe_connect_account_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='partner',
            name='stripe_connect_charges_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partner',
            name='stripe_connect_details_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partner',
            name='stripe_connect_onboarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partner',
            name='stripe_connect_payouts_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
