# Generated by Django 5.2.13 on 2026-05-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0002_partner_stripe_connect_account_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="pro_section",
            field=models.CharField(
                choices=[
                    ("restaurant", "Restaurant"),
                    ("nightlife", "Nightlife"),
                    ("activity", "Activite"),
                ],
                default="activity",
                max_length=20,
            ),
        ),
    ]
