# Generated by Django 5.2.13 on 2026-05-23

from django.db import migrations


def _guess_section(category, has_active_venue):
    text = (category or "").lower()
    if "night" in text:
        return "nightlife"
    if "rest" in text:
        return "restaurant"
    if any(token in text for token in ["activ", "kart", "laser", "escape", "bowling", "paintball", "sort"]):
        return "activity"
    if has_active_venue:
        return "restaurant"
    return "activity"


def backfill_partner_pro_section(apps, schema_editor):
    Partner = apps.get_model("partners", "Partner")
    RestaurantVenue = apps.get_model("restaurants", "RestaurantVenue")

    for partner in Partner.objects.all().iterator():
        owner_id = getattr(partner, "owner_id", None)
        has_active_venue = False
        if owner_id:
            has_active_venue = RestaurantVenue.objects.filter(owner_id=owner_id, is_active=True).exists()

        section = _guess_section(getattr(partner, "category", ""), has_active_venue)
        if partner.pro_section != section:
            partner.pro_section = section
            partner.save(update_fields=["pro_section", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0003_partner_pro_section"),
        ("restaurants", "0005_seed_more_lesquinade_photos"),
    ]

    operations = [
        migrations.RunPython(backfill_partner_pro_section, migrations.RunPython.noop),
    ]
