# Generated by Django 5.2.13 on 2026-05-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0004_backfill_partner_pro_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="pro_offer_tier",
            field=models.CharField(
                choices=[
                    ("low", "Offre basse"),
                    ("mid", "Offre moyenne"),
                    ("high", "Offre haute"),
                ],
                default="mid",
                max_length=10,
            ),
        ),
    ]
