# Generated by Django 5.2.13 on 2026-05-23

from django.db import migrations


def _guess_offer_tier(category, short_description, description):
    text = " ".join([category or "", short_description or "", description or ""]).lower()
    if any(token in text for token in ["elite", "premium", "enterprise", "haute"]):
        return "high"
    if any(token in text for token in ["starter", "basic", "essentiel", "basse"]):
        return "low"
    if any(token in text for token in ["pro", "activite 2", "moyenne"]):
        return "mid"
    return "mid"


def backfill_partner_pro_offer_tier(apps, schema_editor):
    Partner = apps.get_model("partners", "Partner")
    for partner in Partner.objects.all().iterator():
        tier = _guess_offer_tier(
            getattr(partner, "category", ""),
            getattr(partner, "short_description", ""),
            getattr(partner, "description", ""),
        )
        if partner.pro_offer_tier != tier:
            partner.pro_offer_tier = tier
            partner.save(update_fields=["pro_offer_tier", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0005_partner_pro_offer_tier"),
    ]

    operations = [
        migrations.RunPython(backfill_partner_pro_offer_tier, migrations.RunPython.noop),
    ]
