# Generated by Django 5.2.13 on 2026-05-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('source', models.CharField(default='openagenda', help_text='Data source identifier.', max_length=50)),
                ('source_id', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('city', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('cover_image_url', models.URLField(blank=True)),
                ('external_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('EXPIRED', 'Expiré'), ('CANCELLED', 'Annulé')], default='ACTIVE', max_length=20)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'public_events_event',
                'ordering': ['starts_at'],
            },
        ),
    ]
