# Generated by Django 5.2.13 on 2026-05-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('city', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('OPEN', 'Ouverte'), ('CLOSED', 'Fermée'), ('ARCHIVED', 'Archivée')], default='OPEN', max_length=20)),
                ('partner_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partner opportunity',
                'verbose_name_plural': 'Partner opportunities',
                'db_table': 'partner_opportunities_opportunity',
                'ordering': ['-created_at'],
            },
        ),
    ]
