# Generated by Django 5.2.13 on 2026-05-15 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.PositiveIntegerField(blank=True, null=True)),
                ('event_id', models.PositiveIntegerField(blank=True, null=True)),
                ('sortie_id', models.PositiveIntegerField(blank=True, null=True)),
                ('qr_token', models.CharField(editable=False, max_length=64, unique=True)),
                ('qr_payload', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ACTIVE', 'Actif'), ('USED', 'Utilise'), ('CANCELLED', 'Annule')], default='PENDING', max_length=20)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tickets_ticket',
                'ordering': ['-created_at'],
            },
        ),
    ]
