# Generated by Django 5.2.13 on 2026-05-15 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketScanAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_token', models.CharField(blank=True, max_length=80)),
                ('outcome', models.CharField(choices=[('SUCCESS', 'Succes'), ('NOT_FOUND', 'Ticket introuvable'), ('INVALID_STATUS', 'Ticket invalide'), ('FORBIDDEN_SCOPE', 'Hors perimetre operateur'), ('MISSING_TOKEN', 'Token manquant')], max_length=24)),
                ('reason_code', models.CharField(blank=True, max_length=60)),
                ('source', models.CharField(choices=[('WEB', 'Interface web'), ('API', 'API')], default='WEB', max_length=10)),
                ('operator_city', models.CharField(blank=True, max_length=100)),
                ('target_city', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_scan_audits', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_audits', to='tickets.ticket')),
            ],
            options={
                'db_table': 'tickets_scan_audit',
                'ordering': ['-created_at'],
            },
        ),
    ]
