# Generated by Django 5.2.13 on 2026-05-15 20:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SponsoredEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('event_id', models.PositiveIntegerField()),
                ('slot_name', models.CharField(default='homepage', max_length=40)),
                ('budget_eur', models.PositiveIntegerField(default=30)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('ACTIVE', 'Active'), ('PAUSED', 'En pause'), ('ENDED', 'Terminee')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ads_sponsored_event',
                'ordering': ['-created_at'],
            },
        ),
    ]
