#!/usr/bin/env python3
"""Generate secure secrets for a Mooviogo production deployment.

Outputs to stdout (safe to redirect / pipe to a secrets manager). Never commit
the result.

Usage:
    python scripts/generate_prod_secrets.py
"""

import secrets
import sys


def gen_secret_key(length: int = 64) -> str:
    return secrets.token_urlsafe(length)


def gen_data_encryption_key() -> str:
    from cryptography.fernet import Fernet
    return Fernet.generate_key().decode("ascii")


def gen_vapid() -> tuple[str, str]:
    """Generate a VAPID P-256 keypair (public + private), urlsafe-b64 raw form."""
    import base64
    from cryptography.hazmat.primitives.asymmetric import ec
    from cryptography.hazmat.primitives import serialization

    private_key = ec.generate_private_key(ec.SECP256R1())

    # Private key: PKCS8 PEM... but pywebpush accepts the raw 32-byte d value
    # base64url-encoded. We emit both for convenience.
    private_numbers = private_key.private_numbers()
    private_value = private_numbers.private_value.to_bytes(32, "big")
    private_b64 = base64.urlsafe_b64encode(private_value).rstrip(b"=").decode("ascii")

    public_key = private_key.public_key()
    public_bytes = public_key.public_bytes(
        encoding=serialization.Encoding.X962,
        format=serialization.PublicFormat.UncompressedPoint,
    )
    public_b64 = base64.urlsafe_b64encode(public_bytes).rstrip(b"=").decode("ascii")

    return public_b64, private_b64


def main() -> int:
    sk = gen_secret_key()
    dek = gen_data_encryption_key()
    vap_pub, vap_priv = gen_vapid()

    print("# ─── Mooviogo production secrets ──────────────────────────────────")
    print("# Generated by scripts/generate_prod_secrets.py")
    print("# Copy into your secrets manager / .env.production. DO NOT COMMIT.")
    print()
    print(f"SECRET_KEY={sk}")
    print(f"DATA_ENCRYPTION_KEY={dek}")
    print(f"WEB_PUSH_VAPID_PUBLIC_KEY={vap_pub}")
    print(f"WEB_PUSH_VAPID_PRIVATE_KEY={vap_priv}")
    print()
    print("# Postgres password (managed services usually generate one for you):")
    print(f"POSTGRES_PASSWORD={secrets.token_urlsafe(32)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
