# Generated by Django 5.2.13 on 2026-05-03 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('city', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(choices=[('COMMUNAUTAIRE', 'Communautaire'), ('PARTENAIRE', 'Partenaire')], default='COMMUNAUTAIRE', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('OPEN', 'Ouverte'), ('FULL', 'Complète'), ('CANCELLED', 'Annulée'), ('COMPLETED', 'Terminée')], default='DRAFT', max_length=20)),
                ('price', models.PositiveIntegerField(default=0, help_text='Price in cents. 0 = free.')),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('cover_image_url', models.URLField(blank=True)),
                ('is_free', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sorties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sorties_sortie',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SortieParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INTERESTED', 'Intéressé'), ('CONFIRMED', 'Confirmé'), ('CANCELLED', 'Annulé')], default='INTERESTED', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('sortie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='sorties.sortie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sorties_participant',
                'unique_together': {('sortie', 'user')},
            },
        ),
    ]
