# Generated by Django 5.2.13 on 2026-05-18 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_partner_stripe_connect_account_id_and_more'),
        ('sorties', '0002_sortie_geolocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortie',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorties', to='partners.partner'),
        ),
    ]
