# Generated by Django 5.2.13 on 2026-05-03 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('SORTIE', 'Sortie'), ('RESTAURANT', 'Restaurant'), ('ACTIVITY', 'Activité')], max_length=20)),
                ('sortie_id', models.PositiveIntegerField(blank=True, null=True)),
                ('restaurant_slot_id', models.PositiveIntegerField(blank=True, null=True)),
                ('activity_session_id', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmée'), ('CANCELLED', 'Annulée'), ('REFUNDED', 'Remboursée')], default='PENDING', max_length=20)),
                ('amount', models.PositiveIntegerField(default=0, help_text='Amount in cents.')),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookings_booking',
                'ordering': ['-created_at'],
            },
        ),
    ]
