# Generated by GitHub Copilot on 2026-05-23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0001_initial"),
        ("sorties", "0001_initial"),
        ("bookings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerAgendaEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source", models.CharField(choices=[("MOOVIOGO", "Mooviogo"), ("DIRECT", "Direct")], default="DIRECT", max_length=20)),
                (
                    "reservation_kind",
                    models.CharField(
                        choices=[
                            ("RESTAURANT", "Restaurant"),
                            ("NIGHTLIFE", "Nightlife"),
                            ("ACTIVITY", "Activité"),
                            ("OTHER", "Autre"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "En attente"), ("CONFIRMED", "Confirmée"), ("CANCELLED", "Annulée")],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("customer_name", models.CharField(blank=True, max_length=120)),
                ("customer_contact", models.CharField(blank=True, max_length=120)),
                ("party_size", models.PositiveIntegerField(blank=True, null=True)),
                ("starts_at", models.DateTimeField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_partner_agenda_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "linked_sortie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partner_agenda_entries",
                        to="sorties.sortie",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_agenda_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agenda_entries",
                        to="partners.partner",
                    ),
                ),
            ],
            options={
                "db_table": "bookings_partner_agenda_entry",
                "ordering": ["starts_at", "-created_at"],
            },
        ),
    ]
