# Generated by Django 5.2.13 on 2026-05-15 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('USER', 'Utilisateur'), ('SORTIE', 'Sortie'), ('EVENT', 'Evenement'), ('MESSAGE', 'Message')], max_length=20)),
                ('target_id', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('SPAM', 'Spam'), ('HARASSMENT', 'Harcelement'), ('DANGEROUS', 'Comportement dangereux'), ('SCAM', 'Arnaque'), ('OTHER', 'Autre')], default='OTHER', max_length=20)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Ouvert'), ('IN_REVIEW', 'En cours'), ('RESOLVED', 'Traite'), ('DISMISSED', 'Rejete')], default='OPEN', max_length=20)),
                ('moderation_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports_report',
                'ordering': ['-created_at'],
            },
        ),
    ]
