# Generated by Django 5.2.13 on 2026-05-15 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='assigned_moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='decision_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='report',
            name='evidence_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='resolution_code',
            field=models.CharField(choices=[('NONE', 'Aucune'), ('RESOLVED_NO_ACTION', 'Traite sans action'), ('DISMISSED_NO_VIOLATION', 'Rejete sans violation'), ('USER_BANNED', 'Utilisateur banni'), ('USER_TEMP_SUSPENDED', 'Utilisateur suspendu'), ('CONTENT_REMOVED', 'Contenu retire')], default='NONE', max_length=40),
        ),
        migrations.AddField(
            model_name='report',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='sla_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='suspension_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
