# Generated by Django 5.2.13 on 2026-05-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_assigned_moderator_report_decision_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='evidence_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/evidence/%Y/%m/%d'),
        ),
    ]
